from .client import DuckChat, guard_reasoning_mode
from .exceptions import (
    APIError,
    ChallengeError,
    ConversationLimitError,
    DuckChatError,
    RateLimitError,
)
from .models import (
    MODEL_ALIASES,
    History,
    ImagePart,
    Message,
    ModelType,
    Role,
    claude,
    claude_haiku,
    gemma,
    gpt5,
    gpt5_luna,
    gpt5_mini,
    gpt5_nano,
    gpt_oss,
    gpt_oss_120b,
    image_generation,
    list_models,
    luna,
    mistral,
    mistral_small,
    model_supports_reasoning,
    model_supports_vision,
    model_supports_web_search,
    nano,
    resolve_effort,
    resolve_model,
)

__version__ = "1.3.1"

__all__ = [
    "DuckChat",
    "guard_reasoning_mode",
    "ModelType",
    "Role",
    "Message",
    "History",
    "ImagePart",
    "DuckChatError",
    "ChallengeError",
    "RateLimitError",
    "ConversationLimitError",
    "APIError",
    "resolve_model",
    "resolve_effort",
    "model_supports_reasoning",
    "model_supports_vision",
    "model_supports_web_search",
    "list_models",
    "MODEL_ALIASES",
    "gpt5",
    "gpt5_luna",
    "luna",
    "gpt5_mini",
    "gpt5_nano",
    "nano",
    "claude",
    "claude_haiku",
    "mistral",
    "mistral_small",
    "gpt_oss",
    "gpt_oss_120b",
    "gemma",
    "image_generation",
    "__version__",
]
